name: Waka Readme

on:
  schedule:
    - cron: "0 18 * * 1"
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROJECTS: "False"
          SHOW_TIMEZONE: "False"
          SHOW_EDITORS: "False"
          SHOW_LOC_CHART: "False"
          SHOW_LANGUAGE_CHART: "False"
          SHOW_OS: "False"
          #SHOW_TOTAL_CODE_TIME: "False"
          SHOW_PROFILE_VIEWS: "False"
          #SHOW_LANGUAGE: "False"

  update-readme-file:
    name: Update README.md File
    runs-on: ubuntu-latest
    needs: update-readme
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Remove specific lines from README.md
        run: |
          git pull
          sed -i '/🚫 Not Opted to Hire/{N;d;}' README.md
          sed -i '/\!\[Code Time\]/d' README.md
          sed -i '/📊 \*\*This Week I Spent My Time On\*\*/{N;N;N;N;N;N;d;}' README.md
          echo "README.md update attempted"

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update README.md: Remove specific lines" && git push)
